---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix_web on your system.
  homepage: https://robertdebock.nl/
  topics: zabbix, web, monitoring, ansible, molecule, tox, playbook
