---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - n=0 ; until [ "$n" = 3 ] ; do tox --parallel all && break ; n=$((n+1)) ; done

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "wBJxuSanAceXnfw4iSQcqK9jkspJ0FeRNFdeLWNvvhJO6t90uUAPhCeid851IvP6VjG3sLcFBQe9skuLqlKQ/Pd7m/5WQTFPqXGoqNOrU8GsIEKEMWS7K0RnlADxF4OIHLNJf6mBbE4sskhSk7Fh0Cx26fd0YL+w8/rkBOAej7oh6IhavbgOlNpo8PXr+jDMWUI5R30Is7RzeE5ffby7Ff3IxlT5waMudQJCfOQMU6Q31qRHTkQvEJujzZPp918n9Z0R+t+xzXerKMlhcqC3g5V3ziSrayt0ylLrsZsl1hpCGViBE01G6ksi1UM36a84ZduTcxF5JAkYj+F3QyVuJMAb2MP337TPPClFu7n3VvZ20DJDtiOrk+lsKaYItPGN+C6b2gclA4xBXW+uX5dasDo7v93miGsd2fBCMiAPJM2uEO8F3ekRTSWdCmfOxAqWbM2Le3+jlD8b1zPxudqcf9AzsNv1/Mib8EGK1c56LI34fg6kbhBN67oWKiD8RaKaqfgWof/DTY6VzN/dsyyCHCrrzkDMUHi5wVzz9MXpH6KkgtywhjwMVJ1SYk0uVTgD9vBED7Z4wCRsfDPx5/DJfYKlQs0GiSogZxFNUou8SYSzt8A2r3qZ4OyJ/HdhFq46IhYiRSFtZDbNhYHbVs9NspGeOjQMmjtco4qQ290HqZ8="
  email: false
