---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="alpine-latest" expectation="fail"
  - version="" distro="alpine-latest" expectation="fail"
  - version="devel" distro="alpine-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
  - version="" distro="alpine-edge" expectation="fail"
  - version="devel" distro="alpine-edge" expectation="fail"
  - version=">=2.7,<2.8" distro="archlinux" expectation="fail"
  - version="" distro="archlinux" expectation="fail"
  - version="devel" distro="archlinux" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-6" expectation="fail"
  - version="" distro="centos-6" expectation="fail"
  - version="devel" distro="centos-6" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.7,<2.8" distro="debian-latest"
  - version="" distro="debian-latest"
  - version="devel" distro="debian-latest"
  - version=">=2.7,<2.8" distro="debian-stable"
  - version="" distro="debian-stable"
  - version="devel" distro="debian-stable"
  - version=">=2.7,<2.8" distro="debian-unstable"
  - version="" distro="debian-unstable"
  - version="devel" distro="debian-unstable"
  - version=">=2.7,<2.8" distro="fedora-latest" expectation="fail"
  - version="" distro="fedora-latest" expectation="fail"
  - version="devel" distro="fedora-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="fedora-rawhide" expectation="fail"
  - version="" distro="fedora-rawhide" expectation="fail"
  - version="devel" distro="fedora-rawhide" expectation="fail"
  - version=">=2.7,<2.8" distro="opensuse-leap" expectation="fail"
  - version="" distro="opensuse-leap" expectation="fail"
  - version="devel" distro="opensuse-leap" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-rolling" expectation="fail"
  - version="" distro="ubuntu-rolling" expectation="fail"
  - version="devel" distro="ubuntu-rolling" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-latest"
  - version="" distro="ubuntu-latest"
  - version="devel" distro="ubuntu-latest"
  - version=">=2.7,<2.8" distro="ubuntu-devel"
  - version="" distro="ubuntu-devel"
  - version="devel" distro="ubuntu-devel"

matrix:
  allow_failures:
    - env: version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
    - env: version="" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-latest" expectation="fail"
    - env: version="devel" distro="archlinux" expectation="fail"
    - env: version="devel" distro="centos-6" expectation="fail"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-latest"
    - env: version="devel" distro="debian-stable"
    - env: version=">=2.7,<2.8" distro="debian-unstable"
    - env: version="" distro="debian-unstable"
    - env: version="devel" distro="debian-unstable"
    - env: version="devel" distro="fedora-latest" expectation="fail"
    - env: version=">=2.7,<2.8" distro="fedora-rawhide" expectation="fail"
    - env: version="" distro="fedora-rawhide" expectation="fail"
    - env: version="devel" distro="fedora-rawhide" expectation="fail"
    - env: version="devel" distro="opensuse-leap" expectation="fail"
    - env: version="devel" distro="ubuntu-rolling" expectation="fail"
    - env: version=">=2.7,<2.8" distro="ubuntu-devel"
    - env: version="" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "Yvnx55vR88xKIkwGMM8sRAuMXhknG7wxCG2fIeYCSc0dVzYecJj2+LU6305jy7ucitw1Seun7LaOE3S9BgX9QcYEEgIHy/WxLzLfHKvHEP45gMfLSHB6Vr1f+a8gdgQ1Wjwi2vyurH6EyAh6E7vDUuEmFKylaI2pSE4T4JZ4oqUDtHbeXMladVYfh7CyBSPA93VFL6h9jSFtcPXtRJnJvZlQYYnkwvLMdZilBNQIFhxxVHnnyrKMJoB4mC/EJSSqBuN+dfRzoKihgUtnGzaJjmUDXDH7hgd2IS9oHUNUhu2et4/wzWyCYrVWonFpvZrn0g6MhQDlRi+CP6BaRWOZcjMKnsNMPirByfM0RG8J0V5xG/XjFAeg6xYa4m1PqQo0Lr9ZJTPUmi6AwFt/ShXMpT1nqTcKxoUDA4UzDD7T7Gs147tiqtcfl9zgN/iSH/xqRZSmQ8TvNeoDgCoMjlqAXZ2VbU4DlKn0JlEapGV/AjIy6tVO29SBr4GNTOPmVX5XbXNHm4+iqfiR6+/naCjYPRXYtaBG5GUELeZQYTY+AW6+tf5hEGHH7s1pIoQ+ck4enkySEvtZ1Ii7S9OblCG3tQN+XMouEMEBw1K24UseHhzqxSdUn7tXTcs/nk1SQdlugU3UanJqZzI+6U49xUEfBqoNO/oF5ER5YXnLXeosBw4="
  email: false
