---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "OvR6wVM7zMlaue+NLFDa8ln55ak9heydZwgEj5eudtoudu7IcTjb8ai3RkDyMiIHCZCCAKD9D1glBCSrxms4EqCjnrbkA1PStYFBY7j4jU5OdHHGAdkg5UV4P9gDZx6k1hNR+hRWsnr3YAFkLqLxi86uusIuCxMu4wvilpKQ+ijoCLnkXO8q9lq8c8M+RvgZQLzwLOGEc59DQjsGyesCDgmro5DA6PtN2BpcNPCYNI6ELs5riuYDMif6aGk64tAMh25oStDvCySoTqHT92tfevsmVT/P+Yih9cgj2G781z7SnzTCGUOElwyNfBX4DPlDukv+nMdsEmgULOTHQ1k8rlYYh/WXCPnJSb7O5n50l4kxnNSb13UhSMnHHvzrktdid6a1mpUTcpSyYKwL6Xtu4dUf6ng6HrMCYDUTFvejrhybbuyh1ayEtrh6eFvukF+B6i5AofoGsAZvKYaeLPPs6OrJ6spBhCAvbc65by+qxoDEwg/Fmi1m1LCN2mtNXS+HA9W+UC6nfoAxx9XzWl9QcpaPBFhTce6mqbsvbZPDMwtavxDlRzxKYf6eOOkqBbS/Xol9mE8YVQ4KPkXzJ8FC5ht3fFCRotMgwBRURC2fua0jSNvp2jzAM6kcKiyLyGlHEJPzMwv6xaOJrYeIaTtWPk8C4Lv+seiLQiq1Rw+PVg8="
  email: false
