---
- name: test if zabbix_web_database_name is set correctly
  assert:
    that:
      - zabbix_web_database_name is defined
      - zabbix_web_database_name | length > 0

- name: test if zabbix_web_database_user is set correctly
  assert:
    that:
      - zabbix_web_database_user is defined
      - zabbix_web_database_user | length > 0

- name: test if zabbix_web_database_pass is set correctly
  assert:
    that:
      - zabbix_web_database_pass is defined
      - zabbix_web_database_pass | length > 0

- name: test if zabbix_web_mysql_connection is set correctly
  assert:
    that:
      - zabbix_web_mysql_connection is defined
      - zabbix_web_mysql_connection | length > 0
      - zabbix_web_mysql_connection in ["network", "socket"]

- name: test if zabbix_web_database_host is set correctly
  assert:
    that:
      - zabbix_web_database_host is defined
      - zabbix_web_database_host | length > 0
  when:
    - zabbix_web_mysql_connection == "network"
