---
- name: test if zabbix_web_database_name is set correctly
  assert:
    that:
      - zabbix_web_database_name is defined
    quiet: yes

- name: test if zabbix_web_database_user is set correctly
  assert:
    that:
      - zabbix_web_database_user is defined
    quiet: yes

- name: test if zabbix_web_database_pass is set correctly
  assert:
    that:
      - zabbix_web_database_pass is defined
    quiet: yes

- name: test if zabbix_web_mysql_connection is set correctly
  assert:
    that:
      - zabbix_web_mysql_connection is defined
      - zabbix_web_mysql_connection in [ "network", "socket" ]
    quiet: yes

- name: test if zabbix_web_database_host is set correctly
  assert:
    that:
      - zabbix_web_database_host is defined
    quiet: yes
  when:
    - zabbix_web_mysql_connection == "network"
