---
# tasks file for zabbix_web
- name: test veriables and environment
  assert:
    that:
      - zabbix_web_database_host is defined
      - zabbix_web_database_port >= 0
      - zabbix_web_database_port <= 65536
      - zabbix_web_database_name is defined
      - zabbix_web_database_user is defined
      - zabbix_web_database_pass is defined
      - zabbix_web_server is defined
      - zabbix_web_username is defined
      - zabbix_web_password is defined
      - zabbix_web_validate_certs or
        not zabbix_web_validate_certs

- name: install zabbix_web
  package:
    name: "{{ zabbix_web_packages }}"
    state: "{{ zabbix_web_package_state }}"
  register: zabbix_web_install_zabbix_web
  until: zabbix_web_install_zabbix_web is succeeded
  retries: 3

- name: configure zabbix_web
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
  notify:
    - restart httpd

- name: install zabbix-api requirements
  pip:
    name: zabbix-api
    state: "{{ zabbix_web_package_state }}"
  register: zabbix_install_zabbix_api_requirements
  retries: 3
  until: zabbix_install_zabbix_api_requirements is succeeded
  when:
    - zabbix_web_groups is defined or
      zabbix_web_hosts is defined

- name: add zabbix groups
  zabbix_group:
    server_url: "{{ zabbix_web_server }}"
    login_user: "{{ zabbix_web_username }}"
    login_password: "{{ zabbix_web_password }}"
    validate_certs: "{{ zabbix_validate_certs }}"
    state: present
    host_groups:
      - "{{ item.name }}"
  with_items:
    - "{{ zabbix_web_groups }}"
  when:
    - zabbix_web_groups is defined
    - ansible_virtualization_type != "docker" or zabbix_web_ignore_docker
  run_once: yes

- name: add zabbix hosts
  zabbix_host:
    server_url: "{{ zabbix_web_server }}"
    login_user: "{{ zabbix_web_username }}"
    login_password: "{{ zabbix_web_password }}"
    validate_certs: "{{ zabbix_validate_certs }}"
    host_name: "{{ item.name }}"
    visible_name: "{{ item.visible_name | default(item.name) }}"
    description: "{{ item.description | default([omit]) }}"
    host_groups:
      - "{{ item.groups }}"
    link_templates:
      - "{{ item.link_templates }}"
    status: enabled
    state: present
    inventory_mode: manual
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ item.interface_ip | default([omit]) }}"
        dns: "{{ item.interface_dns }} | default([omit]) }}"
        port: 10050
  with_items:
    - "{{ zabbix_web_hosts }}"
  when:
    - zabbix_web_groups is defined
    - ansible_virtualization_type != "docker" or zabbix_web_ignore_docker
  run_once: yes
