---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check web interface
      ansible.builtin.uri:
        url: "http://localhost/zabbix"
        return_content: true
      register: zabbix_web_check_web_interface
      failed_when:
        - "'Zabbix SIA' not in zabbix_web_check_web_interface.content"
        - "'Connection refused' in zabbix_web_check_web_interface.content"
