---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check web interface
      uri:
        url: "https://localhost/zabbix"
        return_content: yes
      register: zabbix_web_check_web_interface
      failed_when:
        - "'Zabbix SIA' not in zabbix_web_check_web_interface.content"
