---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check web interface
      ansible.builtin.uri:
        url: "http://localhost/zabbix"
        return_content: yes
      register: zabbix_web_check_web_interface
      failed_when:
        - "'Zabbix SIA' not in zabbix_web_check_web_interface.content"
        - "'Connection refused' in zabbix_web_check_web_interface.content"
