---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: zabbix_web-alpine-latest
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        zabbix_web_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: alpine-latest
